name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  workflow_dispatch:
  push:
    branches:
      - dev-version-*
    paths:
      - gradle.properties

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    with:
      build-target: 'Docker,Sonatype'
      docker-username: ${{ github.actor }}
      devRelease: true
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}