name: Dev release build and publish - Docker and Sonatype

on:
  push:
    tags:
      - \d+.\d+.\d+-dev

jobs:
  build:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    with:
      build-target: 'Docker'
      runsOn: ubuntu-latest
      gradleVersion: '7'
      docker-username: ${{ github.actor }}
      devRelease: true
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}