name: Dev build and publish release to Github

on:
  push:
    branches-ignore:
      - master
      - version-*
jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Sonatype'
      runsOn: ubuntu-latest
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}